services:
  lb:
    image: nginx:1.27-alpine
    platform: linux/amd64
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 30M

  db-ready:
    image: postgres:18-alpine
    platform: linux/amd64
    depends_on:
      - db
    command: sh -c 'until pg_isready -h db -U rinha2026; do sleep 1; done'

  api1:
    image: ghcr.io/toto9in/crab-antiagiota:latest
    platform: linux/amd64
    depends_on:
      db-ready:
        condition: service_completed_successfully
    environment:
      PORT: "3000"
      DATABASE_URL: postgres://rinha2026:rinha2026@db:5432/rinha2026
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 100M

  api2:
    image: ghcr.io/toto9in/crab-antiagiota:latest
    platform: linux/amd64
    depends_on:
      db-ready:
        condition: service_completed_successfully
    environment:
      PORT: "3000"
      DATABASE_URL: postgres://rinha2026:rinha2026@db:5432/rinha2026
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 100M

  db:
    image: ghcr.io/toto9in/crab-antiagiota-db:latest
    platform: linux/amd64
    environment:
      POSTGRES_DB: rinha2026
      POSTGRES_PASSWORD: rinha2026
      POSTGRES_USER: rinha2026
    ports:
      - "55432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: 120M
